version: "3"

services:
  mysql:
    image: mysql:5.6
    volumes:
      - db_data:/var/lib/mysql
      - ./etc/mysql/conf.d:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
    restart: always

  vtiger:
    build: .
    ports:
      - "80:80"

volumes:
  db_data:
