version: "3"

services:
  donkey:
    build:
      context: mariadb
      dockerfile: Dockerfile
    volumes:
      - vtiger_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=vtiger
    restart: always

  vtiger:
    build:
      context: vtiger
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - MYSQL_USER=root
      - MYSQL_PWD=secret

  # test:
  #   image: mysql:8
  #   restart: always
  #   environment:
  #     - MYSQL_USER=root
  #     - MYSQL_PWD=secret
  #   command: |
  #     sleep 60
  #     mysql --host=donkey --execute="show databases;"

volumes:
  vtiger_data:
