---
apiVersion: v1
kind: Service
metadata:
  name: vtiger
spec:
  selector:
    app: vtiger
  ports:
  - name: vtiger-http
    port: 7990
    targetPort: vtiger-http
  - name: vtiger-ssh
    port: 2222
    targetPort: vtiger-ssh
  type: LoadBalancer
  # type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306